# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT	# define $script variable
	# fetching essentials packages for cmake environment environment
	yum -y install epel-release centos-release-scl yum-utils
	yum-config-manager --enable rhel-server-rhscl-7-rpms
	yum -y install devtoolset-7 gcc-c++ yum-utils

	echo -e '#!/bin/bash\nscl enable devtoolset-7 bash' > /etc/profile.d/enabledevtoolset-7.sh
SCRIPT

Vagrant.configure("2") do |config|
	config.vm.provider :virtualbox do |vb|
		vb.name = "steganography"
		vb.memory = 4096
		vb.cpus = 4
	end
	
	config.vm.box = "centos7"
	config.vm.network "private_network", ip: "192.168.2.2"
	config.vm.provision "shell", inline: $script
end
