# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT	# define $script variable
	# fetching essentials packages for cmake environment environment
	yum -y install epel-release
	yum -y install kernel-headers kernel-devel gcc make perl curl wget bzip2 patch net-tools git sudo nfs-utils createrepo
	yum -y install tree vim mlocate
	yum -y update

	# disable selinux
	sed -i 's/SELINUX=.*/SELINUX=disabled/' /etc/selinux/config

SCRIPT

Vagrant.configure("2") do |config|
	config.vm.provider :virtualbox do |vb|
		vb.name = "bare_vagrant_env"
		vb.memory = 16384
		vb.cpus = 6
	end
	
	config.vm.box = "centos/7"
	config.vm.network "private_network", type: "dhcp"
	config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
	config.vm.provision "shell", inline: $script
end
