# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT	# define $script variable
	# fetching essentials packages for cmake environment environment
	yum -y install epel-release
SCRIPT

Vagrant.configure("2") do |config|
	config.vm.provider :virtualbox do |vb|
		vb.name = "bare_vagrant_env"
		vb.memory = 4096
		vb.cpus = 2
	end
	
	config.vm.box = "centos7"
	config.vm.network "private_network", ip: "192.168.2.2"
	config.vm.provision "shell", inline: $script
end
