# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT	# define $script variable
	# fetching essentials packages for cmake environment environment
  yum -y install epel-release
  yum -y install httpd

	# this configures apache to auto start on boot. not needed in vagrant environment
	# due to shared folder being mounted after apache auto start causing apache start up failure 
	# chkconfig --levels 235 httpd on

	sed -i 's@DocumentRoot .*@DocumentRoot "/vagrant/http"@' /etc/httpd/conf/httpd.conf
	sed -i 's@<Directory "/var/www">@<Directory "/vagrant/http">@' /etc/httpd/conf/httpd.conf

	# service httpd start
SCRIPT

Vagrant.configure("2") do |config|
	config.vm.provider :virtualbox do |vb|
		vb.name = "drag_n_drop"
		vb.memory = 4096
		vb.cpus = 2
	end
	
	config.vm.box = "centos7"
	config.vm.network "private_network", ip: "192.168.2.2"
	config.vm.provision "shell", inline: $script
	config.vm.provision "shell", inline: "sudo service httpd start", run: "always"
end
